// <auto-generated />
using System;
using Admin.Repositories.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Admin.Repositories.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20190607212424_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("User.Domain.Model.User", b =>
                {
                    b.Property<Guid>("PartnerUserId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36);

                    b.Property<Guid?>("BeneficiaryId")
                        .HasMaxLength(36);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP");

                    b.Property<Guid>("OfxUserGuid")
                        .HasMaxLength(36);

                    b.Property<Guid>("PartnerAppId")
                        .HasMaxLength(36);

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("PartnerUserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
